# ansible-playbook playbook.yml -l local-pc

- name: Test ansible
  hosts: all
  # connection: local
  # become: true
  gather_facts: true
  vars:
  tasks:
    - name: Debug message
      ansible.builtin.debug:
        msg: "show message"
