#!/bin/bash

clear
url=$1

#echo "All-in-one Download Script for Termux"
#echo "----------Last updated Jan 12 2022----------"
#echo "--------------------------------------------"
#echo "1: Download with youtube-dl"

#read n

#if [ "$n" == '1' ]; then
#[ ! -d "$HOME/storage/downloads/youtube-dl" ] && mkdir "$HOME/storage/downloads/youtube-dl"
#youtube-dl -c -i "$url" -o "$HOME/storage/downloads/youtube-dl/%(title)s.%(ext)s"
#else
#echo "Unrecognized choice"
#fi

#exec 3>&1;
result=$(dialog --clear \
--stdout \
--backtitle "Select" \
--title "Select" \
--menu "Choose:" \
15 60 4 \
1 "video" \
2 "audio");
#2>&1 1>&3);
exitcode=$?;
#exec 3>&-;
#echo $exitcode
#echo $result
#echo $url

#create directory if not exists
[ ! -d "$HOME/storage/downloads/youtube-dl" ] && mkdir "$HOME/storage/downloads/youtube-dl"

if [ "$result" == 1 ]; then
  youtube-dl -c -i "$url" -o "$HOME/storage/downloads/youtube-dl/%(title)s.%(ext)s"
elif [ "$result" == 2 ]; then
  youtube-dl -x --audio-format "mp3" -c -i "$url" -o "$HOME/storage/downloads/youtube-dl/%(title)s.%(ext)s"
else
  echo "Unrecognized choice"
fi
