#!/bin/bash

clear
url=$1
download_path="$HOME/storage/downloads/youtube-dl"

result=$(dialog --clear \
--stdout \
--backtitle "Select" \
--title "Select" \
--menu "Choose:" \
15 60 4 \
1 "video" \
2 "audio");

exitcode=$?;

#create directory if not exists
[ ! -d "$download_path" ] && mkdir "$download_path"

if [ "$result" == 1 ]; then
  yt-dlp -c -i "$url" -o "$download_path/%(title)s.%(ext)s"
elif [ "$result" == 2 ]; then
  yt-dlp -x --audio-format "mp3" -c -i "$url" -o "$download_path/%(title)s.%(ext)s"
else
  echo "Unrecognized choice"
fi
